- hosts: localhost
  become: true
  gather_facts: true

  vars:
    # version_python: "3.12.9"
    version_docker: "28.0.1"
    version_kustomize: "5.6.0"
    kubeflow_kubeconfig: "./kubeflow-mnist/kubeconfig.yaml"

  environment:
    KUBECONFIG: "{{ kubeflow_kubeconfig  }}"

  tasks:
    - import_tasks: tasks/ubuntu.yaml
    # - import_tasks: tasks/kubeflow.yaml
