---
- name: update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install dependencies
  apt:
    name:
      - curl
      - wget
      - ca-certificates
      - git
    state: present

- name: create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  
- name: add docker repo to apt
  block:
    - name: check if docker repo is already added to apt
      ansible.builtin.command: grep -R "download.docker.com/linux/ubuntu" /etc/apt/sources.list.d/
      register: docker_repo_exists
      failed_when: false
      changed_when: false

    - name: add docker repo to apt
      when: docker_repo_exists.rc != 0
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: update apt package list
  apt:
    update_cache: yes

- name: install docker
  apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      # - docker-buildx-plugin 
      - docker-compose-plugin
    state: present

- name: install kind
  block:
    - name: check if kind is installed
      command: which kind
      register: kind_exists
      failed_when: false
      changed_when: false

    - name: install kind
      when: kind_exists.rc != 0
      shell: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v{{ version_kind }}/kind-linux-{{ architecture }} \
        && chmod +x ./kind \
        && sudo mv ./kind /usr/local/bin

- name: install kustomize
  block:
    - name: check if kustomize is installed
      command: which kustomize
      register: kustomize_exists
      failed_when: false
      changed_when: false

    - name: install kustomize
      when: kustomize_exists.rc != 0
      shell: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash \
        && chmod +x kustomize \
        && mv ./kustomize /usr/local/bin

- name: check if kubectl is installed
  command: which kubectl
  register: kubectl_exists
  failed_when: false
  changed_when: false

- name: install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/v{{ version_kubectl }}/bin/linux/{{ architecture }}/kubectl" \
    && chmod +x kubectl \
    && mv ./kubectl /usr/local/bin
  when: kubectl_exists.rc != 0
